### ISSUE TITLE
Feature request: Docker support

### ISSUE THREAD

**Issue by Witteborn** [Uuvana-Studios/longvinter-linux-server#12]
As in my last issue #11 , I have some ideas to make setting up a server even easier.
One of them would be a Docker image or Dockerfile that you can just boot up. This would allow Windows users to set up a Docker container that can itself be Linux-based and host a server with just one or two commands.

Site notes: I'm not sure how the server handles storage files, but I think a Docker volume is also required.

**Comment by WarpWing** [comment]
I'm already working on a beta version of the docker container. Check this out: https://github.com/Uuvana-Studios/longvinter-linux-server/pull/7

**Comment by thomasbnt** [comment]
Hello @Witteborn, you can use https://github.com/tvandoorn/longvinter-docker-server
