### ISSUE TITLE
Longvinter server not listening on any ports

### ISSUE THREAD

**Issue by tvandoorn** [Uuvana-Studios/longvinter-linux-server#16]
**Describe the bug**
I tried setting up a Longvinter server on Linux using both Docker and a Ubuntu 20.04.4 LTS server (clean install in a VM). In both cases the server starts just fine, but it fails to listen on any ports. This makes the server unusable since nobody can connect to it. I tested if the ports are in use with things like curl, telnet and netstat (on both the server itself, and on a different computer). Curl and telnet return a Connection Refused error, and netstat just shows port 22 being in use as that is used for SSH.

I would love to publish my Docker setup for the Linux server and spin up a couple of servers myself, but if I can't get the server software to listen on a port there's not much I can do.

**To Reproduce**
1. Clean install Ubuntu Server 20.04.4 LTS, default settings2. 
2. Copy and paste all commands
3. Start the server using the LongvinterServer.sh script 
4. Run `curl localhost:7777` on the same server, get a connection refused error
5. Run `sudo netstat -tulpn | grep LISTEN` on the same server, the list will not show ports 7777, 27015 and 27016

**Expected behavior**
The server starts just fine, and it is available on ports 7777, 27015 and 27016.

**Screenshots**
None, see link to pastebin below for full server log

**Server (please complete the following information):**
 - OS: Ubuntu Server 20.04.4 LTS
 - Git version: 2.25.1
 - Git LFS version: 2.9.2
 - Steam Version: No idea how to check, but likely the latest as steamcmd updates on startup
 - Server Version: Latest version from Github master branch

**Client (please complete the following information):**
Not relevant

**Additional context**
Full server startup log: https://pastebin.com/BicVTsXN

**Comment by tvandoorn** [comment]
After some more testing with Debian and Windows 10 (both behave the same) it appears the server is reachable from the game without any problems even though it does not appear to be listening on any of the ports.

Closing this issue for now.

**Comment by WarpWing** [comment]
I should note that the server doesn't listen on any ports. It just uses those ports to talk to the main servers.
