### ISSUE TITLE
Steam Version when?

### ISSUE THREAD

**Issue by denizkoekden** [Uuvana-Studios/longvinter-linux-server#19]
Hey,
as I prefer to host all my Gameservers with SteamCMD ( I wrote my own Script for SteamCMD) I saw that there is an Steam Version coming. Can someone tell me when this gets unlocked? https://steamdb.info/app/1639880/depots/?branch=public ?

Regards

**Comment by Jalsson** [comment]
Hi, I have published the tool but for some reason, it wont show up available
