### ISSUE TITLE
Longvinter.service won't work with longvinter.socket

### ISSUE THREAD

**Issue by Yuuki2012** [Uuvana-Studios/longvinter-linux-server#22]
**Describe the bug**
The `longvinter.service` file won't work cuz it's looking for `minecraft.socket` (longvinter.service#L28)

**To Reproduce**
1. Follow Linux installation guide.

**Expected behavior**
Working.

**Screenshots**
-

**Server (please complete the following information):**
 - OS: Linux Mint 20.2 Uma.
 - Git version: 2.25.1
 - Steam Version: whichever is installed with the guide.
 - Server Version: 1.0?

**Client (please complete the following information):**
 - OS: Windows 11
 - Steam Version: latest.
 - Game Version: 1.0.0

**Additional context**
Just change it to longvinter.socket and it'll work, not a big deal, but won't work out of the box atm.

**Comment by WarpWing** [comment]
This should be fixed. Do you know if this is still happening? According to the socket, it should be corrected.

**Comment by Yuuki2012** [comment]
Yeah it's fixed lol. I posted it before they fixed it. I'll close the issue.
