### ISSUE TITLE
Setting IP addresses & ports

### ISSUE THREAD

**Issue by JimTR** [Uuvana-Studios/longvinter-linux-server#24]
Hi,
the game appears to listen on all interfaces (0.0.0.0) is it possible to to force the game to use a specific ip ?
The same applies to ports as I may have something already listening on the ports the game appears to use

**Comment by NicoChiGu** [comment]
### **Refer to dockerhub's project**
if you need to listen to other ports
`bash LongvinterServer.sh QueryPort=[Default Port 27016] -port=**[Default Port 7777]**`
