### ISSUE TITLE
High cpu usage

### ISSUE THREAD

**Issue by JimTR** [Uuvana-Studios/longvinter-linux-server#26]
Hi 
as you can see from the image the cpu usage is a bit high 
<img src="https://i.imgur.com/0dWpDiZ.png"></img>
have I not set something up correctly or does the game just hog CPU ?

**Comment by ewrogers** [comment]
It is important to remember that "100%" CPU usage is in the context of a single core. In your case you have a 4c/8t machine, so effectively it's using "50%" of a core or 12.5% of your total CPU.

You can see this represented in the above graphs "1-8" within `htop`. No cause for concern.

**Comment by JimTR** [comment]
ok why did the machine die ? must be my bad hardware

**Comment by JimTR** [comment]
That said this game is not worth supporting I hope your venture is sucessfull
