### ISSUE TITLE
cant start Linux-server

### ISSUE THREAD

**Issue by senlsx** [Uuvana-Studios/longvinter-linux-server#30]
hi there
I'm new for the game server, but a programmer.

I'm looking forward to start a server but I get this：

I'm sure I have done all steps on the turtior in https://docs-server.longvinter.com/linux/setup-vanilla/

but I get this：
4.26.0-0+++UE4+Release-4.26 522 0
Disabling core dumps.
Preparing to exit.Shutting down and abandoning module SandboxFile (6)Shutting down and abandoning module PakFile (4)Shutting down and abandoning module RSA (3)Exiting.Exiting abnormally (error code: 1)

so how can I continue？

**Comment by JustKing009** [comment]
same error with ubuntu server 20.04.4 LTS and ubuntu desktop 20.04.4 LTS

**Comment by jskiweb** [comment]
Same Error on Debian

**Comment by cherryblossom2020** [comment]
Run:
git lfs fetch --all
git lfs pull
