### ISSUE TITLE
LongvinterServer.sh and network-ports.sh not set to executable by default.

### ISSUE THREAD

**Issue by VisibleReality** [Uuvana-Studios/longvinter-linux-server#9]
**Describe the bug**
The files LongvinterServer.sh and network-ports.sh are not set to executable by default.

**To Reproduce**
1. Clone or Pull repository
2. Cannot run LongvinterServer.sh because it is not executable

**Expected behavior**
LongvinterServer.sh and network-ports.sh should be executable by default (like server-autorun.sh and server-crashCheck.sh)

**Screenshots**
File listing after a pull showing that LongvinterServer.sh is not executable
![image](https://user-images.githubusercontent.com/37581230/156489739-cc4325ef-b606-49a3-b762-064af6274496.png)

**Server (please complete the following information):**
 - OS: Ubuntu 20.04 Server
 - Git version 2.25.1
 - Steam Version SteamCMD 1642451655
 - Server Version Latest as of writing this issue (commit [7b4198e](https://github.com/Uuvana-Studios/longvinter-linux-server/commit/7b4198ebda8885b7915b2952cb6d0e55f04614ef))

**Client (please complete the following information):**
Not relevant

**Comment by WarpWing** [comment]
> LongvinterServer.sh and network-ports.sh should be executable by default (like server-autorun.sh and server-crashCheck.sh)

No, this needs to be chmodded or "changed modded" for permission reasons. You need to chmod the script by doing 
```bash
chmod +x scriptname.sh
```
